name: e2e-tests

on: [push, pull_request]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - shell: bash
        run: source tests.sh
        env:
          PROJECT_ID: cl0wihlop3rwc0mtj9np28ti2
          KILI_API_KEY: 93d8d3fa-ed06-410c-b295-9a9310e88fb0
